// Bungapedia marketplace dummy data — realistis, konsisten, siap demo owner.
// Foto reuse hasil harvest lokal (public/assets/images/flowermarketplace.com/*).
// Asumsi didokumentasikan: harga final ID, settlement 10% fee, pengiriman flat.

import type { Customer, MarketProduct, Order, Partner } from './market-types';

const IMG = (f: string) => `${import.meta.env.BASE_URL}assets/images/flowermarketplace.com/${f}`;

export const PLATFORM_FEE = 20000;
export const DELIVERY_FEE = 30000;
export const SETTLEMENT_FEE_RATE = 0.1;

/** Badan hukum pengelola platform (dipilih owner — opsi 1). */
export const COMPANY_LEGAL = 'PT Bunga Pedia Nusantara';

export function rp(n: number): string {
  return 'Rp' + Math.round(n).toLocaleString('id-ID');
}

export type DeliveryTone = 'instant' | 'sameday' | 'nextday' | 'overnight';
export function deliveryTone(est: string): DeliveryTone {
  const s = (est ?? '').toLowerCase();
  if (s.includes('instant')) return 'instant';
  if (s.includes('overnight')) return 'overnight';
  if (s.includes('h+1') || s.includes('besok')) return 'nextday';
  if (s.includes('same-day')) return 'sameday';
  // fallback produksi cepat → instant
  if (s.includes('1–2 jam') || s.includes('1–3 jam')) return 'instant';
  if (s.includes('2–3 jam') || s.includes('2–4 jam')) return 'sameday';
  return 'sameday';
}
export function deliveryShortLabel(est: string): string {
  const t = deliveryTone(est);
  if (t === 'instant') return 'Instant';
  if (t === 'sameday') return 'Same-day';
  if (t === 'nextday') return 'H+1';
  return 'Overnight';
}

/** Normalisasi path gambar lawas (/assets/...) ke BASE_URL.
 *  localStorage pengunjung lama masih menyimpan path absolut pra-fix —
 *  tanpa ini gambar produk tampil rusak di subpath Pages. Self-healing:
 *  hasil normalisasi ditulis balik oleh persist(). */
export function fixImg(src: string): string {
  if (typeof src !== 'string') return src;
  if (src.startsWith('/assets/')) return `${import.meta.env.BASE_URL}${src.slice(1)}`;
  return src;
}

export const CATEGORIES = [
  'Bunga Papan',
  'Standing Flower',
  'Buket',
  'Bunga Ucapan',
  'Hampers',
  'Gift',
];

export const OCCASIONS = [
  'Ulang Tahun',
  'Pernikahan',
  'Wisuda',
  'Anniversary',
  'Congratulations',
  'Duka Cita',
  'Hari Raya',
  'Corporate',
];

export const RECIPIENTS = ['Pasangan', 'Orang Tua', 'Teman', 'Rekan Kerja', 'Klien', 'Keluarga'];

export const PARTNERS: Partner[] = [
  {
    id: 'pt-bunga-sejahtera',
    name: 'Bunga Sejahtera',
    city: 'Jakarta Selatan',
    area: ['Jabodetabek', 'Bandung'],
    logo: IMG('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp'),
    cover: IMG('0b5c95843a684c817befc78c95993fc3-1600-93dc4b0060.webp'),
    verified: true,
    rating: 4.9,
    reviews: 1240,
    orders: 8600,
    responseRate: 98,
    productionTime: '3–5 jam',
    description:
      'Spesialis bunga papan & standing flower untuk corporate dan duka cita. Rangkaian besar, foto QC sebelum kirim, armada sendiri untuk Jabodetabek.',
    since: '2019',
  },
  {
    id: 'pt-flower-house',
    name: 'Flower House',
    city: 'Bandung',
    area: ['Bandung', 'Jabodetabek'],
    logo: IMG('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp'),
    cover: IMG('4142275c5e7d3d072c1283df13388efa-900-cc92a73b92.webp'),
    verified: true,
    rating: 4.8,
    reviews: 860,
    orders: 5200,
    responseRate: 96,
    productionTime: '2–4 jam',
    description:
      'Studio buket premium — mawar impor, peony musiman, dan wrapping editorial. Favorit untuk anniversary & pasangan.',
    since: '2020',
  },
  {
    id: 'pt-kebun-dieng',
    name: 'Kebun Dieng Florist',
    city: 'Wonosobo',
    area: ['Jawa Tengah', 'Jabodetabek'],
    logo: IMG('bc3dff37241196a134e14bc1a6216c62-480-6c122f0e3d.webp'),
    cover: IMG('9caffa42f100ae8ff1e3d86dc3f07c0a-244-cbc225d9a6.webp'),
    verified: true,
    rating: 4.7,
    reviews: 540,
    orders: 3100,
    responseRate: 94,
    productionTime: '4–6 jam',
    description:
      'Petik langsung dari kebun Dieng. Alstroemeria & eucalyptus segar dengan harga petani, cocok untuk event besar.',
    since: '2021',
  },
  {
    id: 'pt-bali-tropis',
    name: 'Bali Tropis Co.',
    city: 'Denpasar',
    area: ['Bali', 'Surabaya'],
    logo: IMG('8d84fb2861423d27749f14c711d40c4f-480-c7aa10aa9b.webp'),
    cover: IMG('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp'),
    verified: false,
    rating: 4.6,
    reviews: 210,
    orders: 980,
    responseRate: 91,
    productionTime: '3–6 jam',
    description:
      'Spesialis rangkaian tropis & anthurium untuk hotel dan wedding outdoor. Menunggu verifikasi dokumen kedua.',
    since: '2023',
  },
  {
    id: 'pt-hampers-kita',
    name: 'Hampers Kita',
    city: 'Jakarta Barat',
    area: ['Jabodetabek'],
    logo: IMG('7cd5cea6b34c5a034509dd7b882df5b0-360-6ab53eb502.webp'),
    cover: IMG('2cb852255ecf8884a12469fd1f89eb78-800-9c63fa88d8.webp'),
    verified: true,
    rating: 4.8,
    reviews: 690,
    orders: 4400,
    responseRate: 97,
    productionTime: '1–3 jam',
    description:
      'Hampers & gift kurasi untuk corporate dan hari raya. Bisa kartu ucapan custom + branding perusahaan.',
    since: '2020',
  },
];

export const partnerById = (id: string): Partner => PARTNERS.find((p) => p.id === id)!;

const G = (f: string) => IMG(f);

export const PRODUCTS: MarketProduct[] = [
  {
    id: 'prd-papan-grand-opening',
    name: 'Bunga Papan Grand Opening Premium',
    slug: 'bunga-papan-grand-opening',
    partnerId: 'pt-bunga-sejahtera',
    price: 450000,
    was: 550000,
    category: 'Bunga Papan',
    occasions: ['Congratulations', 'Corporate'],
    recipients: ['Klien', 'Rekan Kerja'],
    rating: 4.9,
    reviews: 312,
    img: G('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp'),
    gallery: [
      G('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp'),
      G('0b5c95843a684c817befc78c95993fc3-1600-93dc4b0060.webp'),
    ],
    description:
      'Bunga papan 2×1,2 m untuk congratulations & grand opening. Rangkaian penuh, pita custom nama pengirim, foto QC dikirim sebelum pengiriman.',
    materials: 'Mawar, lily, krisan, styrofoam premium',
    size: '200 × 120 cm',
    productionTime: '3–5 jam',
    deliveryArea: ['Jabodetabek', 'Bandung'],
    deliveryEstimate: 'Same-day sebelum 15:00',
    available: true,
    popular: true,
    reviewSnippets: [
      { name: 'Rina', text: 'Rangkaian penuh, tulisan pita rapi. Foto QC dikirim dulu.', rating: 5 },
      { name: 'Dimas', text: 'Sampai tepat waktu untuk opening klien.', rating: 5 },
    ],
  },
  {
    id: 'prd-buket-peony',
    name: 'Buket Peony Sarah Blush',
    slug: 'buket-peony-sarah',
    partnerId: 'pt-flower-house',
    price: 385000,
    category: 'Buket',
    occasions: ['Anniversary', 'Ulang Tahun'],
    recipients: ['Pasangan', 'Orang Tua'],
    rating: 4.9,
    reviews: 204,
    img: G('03c895f62509a1802afade74dde839b2-480-bf5e4a9f9a.webp'),
    gallery: [G('03c895f62509a1802afade74dde839b2-480-bf5e4a9f9a.webp'), G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp')],
    description:
      'Buket peony impor 10 tangkai dengan wrapping linen editorial. Dibeli di fase marshmallow agar mekar pas di hari-H.',
    materials: 'Peony Sarah Bernhardt, eucalyptus, linen wrap',
    size: '12 tangkai · Ø 35 cm',
    productionTime: '2–4 jam',
    deliveryArea: ['Bandung', 'Jabodetabek'],
    deliveryEstimate: 'Same-day / besok pagi',
    available: true,
    popular: true,
    reviewSnippets: [{ name: 'Sinta', text: 'Mekarnya pas banget pas anniversary. Wangi!', rating: 5 }],
  },
  {
    id: 'prd-standing-peach',
    name: 'Standing Flower Juliet Peach',
    slug: 'standing-juliet-peach',
    partnerId: 'pt-flower-house',
    price: 520000,
    was: 640000,
    category: 'Standing Flower',
    occasions: ['Pernikahan', 'Congratulations'],
    recipients: ['Teman', 'Keluarga'],
    rating: 4.8,
    reviews: 167,
    img: G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp'),
    gallery: [G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp')],
    description: 'Standing flower garden rose Juliet — favorit wedding & congratulations. Kaki besi kokoh + pita satin.',
    materials: 'Garden rose, lisianthus, ruscus',
    size: 'Tinggi 160 cm',
    productionTime: '2–4 jam',
    deliveryArea: ['Bandung', 'Jabodetabek'],
    deliveryEstimate: 'H+1 untuk wedding',
    available: true,
    reviewSnippets: [{ name: 'Andi', text: 'Warnanya persis kayak foto katalog.', rating: 5 }],
  },
  {
    id: 'prd-hortensia-putih',
    name: 'Buket Hortensia Putih Wedding',
    slug: 'buket-hortensia-putih',
    partnerId: 'pt-kebun-dieng',
    price: 295000,
    category: 'Buket',
    occasions: ['Pernikahan', 'Anniversary'],
    recipients: ['Pasangan', 'Teman'],
    rating: 4.7,
    reviews: 98,
    img: G('73e7f8d2edb3395bae17a4be4f8b4975-240-7913d5576d.webp'),
    gallery: [G('73e7f8d2edb3395bae17a4be4f8b4975-240-7913d5576d.webp')],
    description: 'Hortensia putih petik pagi dari Batu. Cocok untuk wedding bouquet & dekor meja akad.',
    materials: 'Hortensia putih, baby breath',
    size: '8 tangkai',
    productionTime: '4–6 jam',
    deliveryArea: ['Jawa Tengah', 'Jabodetabek'],
    deliveryEstimate: 'Overnight dingin',
    available: true,
    reviewSnippets: [{ name: 'Putri', text: 'Segar, tahan 6 hari di vas.', rating: 4 }],
  },
  {
    id: 'prd-tulip-double',
    name: 'Buket Tulip Double Pink',
    slug: 'buket-tulip-double-pink',
    partnerId: 'pt-flower-house',
    price: 340000,
    category: 'Buket',
    occasions: ['Ulang Tahun', 'Wisuda'],
    recipients: ['Pasangan', 'Teman'],
    rating: 4.8,
    reviews: 141,
    img: G('7765fbdaac48650bf283a3ff81a126dc-450-a0ccac80a9.webp'),
    gallery: [G('7765fbdaac48650bf283a3ff81a126dc-450-a0ccac80a9.webp')],
    description: 'Tulip double impor — kelopak tumpuk, warna pekat. Best seller wisuda & ulang tahun.',
    materials: 'Tulip double, wrapping kraft premium',
    size: '10 tangkai',
    productionTime: '2–3 jam',
    deliveryArea: ['Bandung', 'Jabodetabek'],
    deliveryEstimate: 'Same-day',
    available: true,
    popular: true,
    reviewSnippets: [{ name: 'Nadia', text: 'Buat wisuda adik, fotonya bagus banget.', rating: 5 }],
  },
  {
    id: 'prd-lily-oriental',
    name: 'Buket Lily Oriental Pink',
    slug: 'buket-lily-oriental',
    partnerId: 'pt-bali-tropis',
    price: 290000,
    was: 360000,
    category: 'Buket',
    occasions: ['Ulang Tahun', 'Hari Raya'],
    recipients: ['Orang Tua', 'Keluarga'],
    rating: 4.6,
    reviews: 87,
    img: G('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp'),
    gallery: [G('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp')],
    description: 'Lily oriental wangi semerbak, 5 tangkai mix kuncup + mekar agar tahan lama.',
    materials: 'Lily oriental, alstroemeria',
    size: '7 tangkai',
    productionTime: '3–6 jam',
    deliveryArea: ['Bali', 'Surabaya'],
    deliveryEstimate: 'Same-day Bali',
    available: true,
    reviewSnippets: [{ name: 'Made', text: 'Wangi satu ruangan.Minus: anter perlu dicabut sendiri.', rating: 4 }],
  },
  {
    id: 'prd-alstro-pink',
    name: 'Buket Alstroemeria Pink Ceria',
    slug: 'buket-alstro-pink',
    partnerId: 'pt-kebun-dieng',
    price: 149000,
    was: 189000,
    category: 'Buket',
    occasions: ['Congratulations', 'Ulang Tahun'],
    recipients: ['Teman', 'Rekan Kerja'],
    rating: 4.7,
    reviews: 112,
    img: G('bc3dff37241196a134e14bc1a6216c62-480-6c122f0e3d.webp'),
    gallery: [G('bc3dff37241196a134e14bc1a6216c62-480-6c122f0e3d.webp')],
    description: 'Alstroemeria tahan 10–14 hari — pilihan hemat tapi awet untuk ucapan selamat.',
    materials: 'Alstroemeria pink, eucalyptus',
    size: '10 tangkai',
    productionTime: '4–6 jam',
    deliveryArea: ['Jawa Tengah', 'Jabodetabek'],
    deliveryEstimate: 'Overnight',
    available: true,
    reviewSnippets: [{ name: 'Fajar', text: 'Awet dua minggu, worth it.', rating: 5 }],
  },
  {
    id: 'prd-alstro-lavender',
    name: 'Buket Alstroemeria Lavender',
    slug: 'buket-alstro-lavender',
    partnerId: 'pt-kebun-dieng',
    price: 159000,
    category: 'Buket',
    occasions: ['Wisuda', 'Anniversary'],
    recipients: ['Teman', 'Pasangan'],
    rating: 4.7,
    reviews: 76,
    img: G('7cd5cea6b34c5a034509dd7b882df5b0-360-6ab53eb502.webp'),
    gallery: [G('7cd5cea6b34c5a034509dd7b882df5b0-360-6ab53eb502.webp')],
    description: 'Varian lavender langka — favorit wisuda & foto. Stok kebun terbatas tiap minggu.',
    materials: 'Alstroemeria lavender',
    size: '10 tangkai',
    productionTime: '4–6 jam',
    deliveryArea: ['Jawa Tengah', 'Jabodetabek'],
    deliveryEstimate: 'Overnight',
    available: true,
    reviewSnippets: [{ name: 'Intan', text: 'Warnanya unik, beda dari buket biasa.', rating: 5 }],
  },
  {
    id: 'prd-anthurium',
    name: 'Standing Anthurium Merah Tropis',
    slug: 'standing-anthurium-merah',
    partnerId: 'pt-bali-tropis',
    price: 275000,
    category: 'Standing Flower',
    occasions: ['Corporate', 'Congratulations'],
    recipients: ['Klien', 'Rekan Kerja'],
    rating: 4.5,
    reviews: 64,
    img: G('8d84fb2861423d27749f14c711d40c4f-480-c7aa10aa9b.webp'),
    gallery: [G('8d84fb2861423d27749f14c711d40c4f-480-c7aa10aa9b.webp')],
    description: 'Rangkaian tropis tahan panas untuk lobby hotel & event outdoor Bali.',
    materials: 'Anthurium, monstera, heliconia',
    size: 'Tinggi 150 cm',
    productionTime: '3–6 jam',
    deliveryArea: ['Bali', 'Surabaya'],
    deliveryEstimate: 'Same-day Bali',
    available: true,
    reviewSnippets: [{ name: 'Wayan', text: 'Tahan 5 hari di lobby outdoor.', rating: 4 }],
  },
  {
    id: 'prd-eucalyptus',
    name: 'Buket Eucalyptus Silver Dollar',
    slug: 'buket-eucalyptus',
    partnerId: 'pt-kebun-dieng',
    price: 135000,
    category: 'Bunga Ucapan',
    occasions: ['Duka Cita', 'Corporate'],
    recipients: ['Keluarga', 'Rekan Kerja'],
    rating: 4.8,
    reviews: 93,
    img: G('9caffa42f100ae8ff1e3d86dc3f07c0a-244-cbc225d9a6.webp'),
    gallery: [G('9caffa42f100ae8ff1e3d86dc3f07c0a-244-cbc225d9a6.webp')],
    description: 'Rangkaian dedaunan elegan & tenang untuk belasungkawa dan dekor minimalis.',
    materials: 'Eucalyptus silver dollar, ruscus',
    size: '15 tangkai',
    productionTime: '4 jam',
    deliveryArea: ['Jawa Tengah', 'Jabodetabek'],
    deliveryEstimate: 'Overnight',
    available: true,
    reviewSnippets: [{ name: 'Hendra', text: 'Sopan dan rapi untuk duka cita.', rating: 5 }],
  },
  {
    id: 'prd-hampers-lebaran',
    name: 'Hampers Lebaran Kurasi Deluxe',
    slug: 'hampers-lebaran-deluxe',
    partnerId: 'pt-hampers-kita',
    price: 575000,
    was: 650000,
    category: 'Hampers',
    occasions: ['Hari Raya', 'Corporate'],
    recipients: ['Klien', 'Orang Tua', 'Keluarga'],
    rating: 4.8,
    reviews: 188,
    img: G('4142275c5e7d3d072c1283df13388efa-900-cc92a73b92.webp'),
    gallery: [G('4142275c5e7d3d072c1283df13388efa-900-cc92a73b92.webp')],
    description: 'Hampers kue premium + teh + buket mini. Box eksklusif, kartu ucapan custom perusahaan.',
    materials: 'Cookies, teh, mini bouquet, box hardcover',
    size: 'Box 40 × 30 cm',
    productionTime: '1–3 jam',
    deliveryArea: ['Jabodetabek'],
    deliveryEstimate: 'Same-day / H+1',
    available: true,
    popular: true,
    reviewSnippets: [{ name: 'HR Maybank', text: 'Pesan 40 box untuk klien, semua rapi.', rating: 5 }],
  },
  {
    id: 'prd-garden-south',
    name: 'Buket Garden Rose South Park',
    slug: 'buket-south-park',
    partnerId: 'pt-flower-house',
    price: 310000,
    was: 395000,
    category: 'Buket',
    occasions: ['Pernikahan', 'Anniversary'],
    recipients: ['Pasangan', 'Teman'],
    rating: 4.8,
    reviews: 129,
    img: G('2cb852255ecf8884a12469fd1f89eb78-800-9c63fa88d8.webp'),
    gallery: [G('2cb852255ecf8884a12469fd1f89eb78-800-9c63fa88d8.webp')],
    description: 'Garden rose South Park — kelopak tumpuk wangi lembut. Favorit bridal & pre-wedding.',
    materials: 'Garden rose, astilbe',
    size: '12 tangkai',
    productionTime: '2–4 jam',
    deliveryArea: ['Bandung', 'Jabodetabek'],
    deliveryEstimate: 'Same-day',
    available: true,
    reviewSnippets: [{ name: 'Clara', text: 'Buat pre-wedding, mekarnya cantik di foto.', rating: 5 }],
  },
  {
    id: 'prd-instant-mawar',
    name: 'Buket Mawar Merah Instant — 1 Jam Sampai',
    slug: 'buket-mawar-instant',
    partnerId: 'pt-hampers-kita',
    price: 425000,
    was: 480000,
    category: 'Buket',
    occasions: ['Ulang Tahun', 'Anniversary', 'Congratulations'],
    recipients: ['Pasangan', 'Orang Tua'],
    rating: 4.9,
    reviews: 203,
    img: G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp'),
    gallery: [G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp'), G('7765fbdaac48650bf283a3ff81a126dc-450-a0ccac80a9.webp')],
    description: 'Buket mawar merah 20 tangkai + kartu ucapan tulis tangan. Kurir standby Jabodetabek — pesan sekarang, 60–90 menit sampai. Foto QC dikirim sebelum jalan.',
    materials: 'Mawar merah premium, baby breath, wrapping kraft',
    size: '20 tangkai · Ø 32 cm',
    productionTime: '15–30 menit',
    deliveryArea: ['Jabodetabek'],
    deliveryEstimate: 'Instant 1–2 jam',
    available: true,
    popular: true,
    reviewSnippets: [
      { name: 'Andra', text: 'Pesan jam 14, jam 15 sudah sampai kantor istri. Kilat!', rating: 5 },
      { name: 'Maya', text: 'Kurir chat dulu, bunganya masih segar pas sampai.', rating: 5 },
    ],
  },
  {
    id: 'prd-instant-lily',
    name: 'Buket Lily Putih Instant — Hadiah Mendadak',
    slug: 'buket-lily-instant',
    partnerId: 'pt-flower-house',
    price: 385000,
    category: 'Buket',
    occasions: ['Ulang Tahun', 'Duka Cita', 'Congratulations'],
    recipients: ['Teman', 'Keluarga'],
    rating: 4.8,
    reviews: 96,
    img: G('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp'),
    gallery: [G('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp')],
    description: 'Lily putih 7 tangkai + eucalyptus. Untuk momen mendadak — chat kurir langsung, estimasi 90 menit. Cocok untuk ucapan duka atau kejutan.',
    materials: 'Lily putih, eucalyptus, wrapping putih',
    size: '7 tangkai',
    productionTime: '20 menit',
    deliveryArea: ['Bandung', 'Jabodetabek'],
    deliveryEstimate: 'Instant 2 jam',
    available: true,
    reviewSnippets: [{ name: 'Dewi', text: 'Butuh cepat untuk melayat, bunganya rapi dan wangi.', rating: 5 }],
  },
  {
    id: 'prd-instant-papan',
    name: 'Bunga Papan Instant — Opening Hari Ini',
    slug: 'bunga-papan-instant',
    partnerId: 'pt-bunga-sejahtera',
    price: 695000,
    category: 'Bunga Papan',
    occasions: ['Congratulations', 'Corporate'],
    recipients: ['Klien', 'Rekan Kerja'],
    rating: 4.9,
    reviews: 58,
    img: G('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp'),
    gallery: [G('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp')],
    description: 'Bunga papan 2×1,2 m ready stock — teks pita custom 15 menit jadi. Armada sendiri Jabodetabek, untuk opening dadakan hari ini.',
    materials: 'Mawar, krisan, styrofoam premium',
    size: '200 × 120 cm',
    productionTime: '30–45 menit',
    deliveryArea: ['Jabodetabek'],
    deliveryEstimate: 'Instant 2–3 jam',
    available: true,
    popular: true,
    reviewSnippets: [{ name: 'Pak Hendra', text: 'Pagi pesan, siang sudah nangkring di lobi ruko. Top!', rating: 5 }],
  },
];

export const productById = (id: string): MarketProduct | undefined => PRODUCTS.find((p) => p.id === id);
export const productsByPartner = (pid: string): MarketProduct[] => PRODUCTS.filter((p) => p.partnerId === pid);

export const CUSTOMERS: Customer[] = [
  { id: 'c-rina', name: 'Rina', city: 'Jakarta' },
  { id: 'c-budi', name: 'Budi', city: 'Bandung' },
  { id: 'c-sinta', name: 'Sinta', city: 'Surabaya' },
  { id: 'c-andi', name: 'Andi', city: 'Jakarta' },
  { id: 'c-putri', name: 'Putri', city: 'Denpasar' },
];

const T = (status: Order['status']): Order['timeline'] => {
  const keys: Order['status'][] = [
    'pending_payment',
    'paid',
    'accepted',
    'preparing',
    'ready',
    'shipped',
    'delivered',
    'completed',
  ];
  const idx = keys.indexOf(status === 'disputed' ? 'shipped' : status);
  return keys.map((k, i) => ({ key: k, at: `12 Sep 2026 · ${9 + i}:0${i % 6}`, done: i <= idx }));
};

export const SEED_ORDERS: Order[] = [
  {
    id: 'INV-2026-001',
    customerId: 'c-rina',
    customerName: 'Rina',
    items: [{ productId: 'prd-buket-peony', name: 'Buket Peony Sarah Blush', img: G('03c895f62509a1802afade74dde839b2-480-bf5e4a9f9a.webp'), price: 385000, qty: 1, partnerId: 'pt-flower-house' }],
    partnerId: 'pt-flower-house',
    productTotal: 385000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 435000,
    recipient: { name: 'Ibu Ratna', phone: '0812xxxxxx', address: 'Jl. Kemang Raya No. 8, Jakarta Selatan' },
    delivery: { date: '14 Sep 2026', time: '10:00–13:00', note: 'Titip satpam jika tidak ada orang' },
    message: 'Selamat ulang tahun, Ibu! Sehat selalu. — Rina',
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'preparing',
    settlement: 'pending',
    createdAt: '12 Sep 2026',
    timeline: T('preparing'),
  },
  {
    id: 'INV-2026-002',
    customerId: 'c-budi',
    customerName: 'Budi',
    items: [{ productId: 'prd-papan-grand-opening', name: 'Bunga Papan Grand Opening Premium', img: G('33366d30ffbd0b9304731257f074f57d-480-146fdb3e85.webp'), price: 450000, qty: 2, partnerId: 'pt-bunga-sejahtera' }],
    partnerId: 'pt-bunga-sejahtera',
    productTotal: 900000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 950000,
    recipient: { name: 'PT Maju Jaya', phone: '0813xxxxxx', address: 'Ruko Daan Mogot KM 12, Jakarta Barat' },
    delivery: { date: '13 Sep 2026', time: '08:00–10:00', note: 'Opening jam 10 pagi' },
    message: 'Congratulations atas grand opening! — Budi & tim',
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    status: 'shipped',
    settlement: 'pending',
    createdAt: '11 Sep 2026',
    timeline: T('shipped'),
  },
  {
    id: 'INV-2026-003',
    customerId: 'c-sinta',
    customerName: 'Sinta',
    items: [{ productId: 'prd-tulip-double', name: 'Buket Tulip Double Pink', img: G('7765fbdaac48650bf283a3ff81a126dc-450-a0ccac80a9.webp'), price: 340000, qty: 1, partnerId: 'pt-flower-house' }],
    partnerId: 'pt-flower-house',
    productTotal: 340000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 390000,
    recipient: { name: 'Nadia', phone: '0815xxxxxx', address: 'Asrama UI Depok' },
    delivery: { date: '12 Sep 2026', time: '13:00–16:00', note: '' },
    message: 'Happy graduation! — Sinta',
    paymentMethod: 'ewallet',
    paymentStatus: 'paid',
    status: 'delivered',
    settlement: 'pending',
    createdAt: '10 Sep 2026',
    timeline: T('delivered'),
  },
  {
    id: 'INV-2026-004',
    customerId: 'c-andi',
    customerName: 'Andi',
    items: [{ productId: 'prd-hampers-lebaran', name: 'Hampers Lebaran Kurasi Deluxe', img: G('4142275c5e7d3d072c1283df13388efa-900-cc92a73b92.webp'), price: 575000, qty: 1, partnerId: 'pt-hampers-kita' }],
    partnerId: 'pt-hampers-kita',
    productTotal: 575000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 625000,
    recipient: { name: 'Klien — Pak Harto', phone: '0811xxxxxx', address: 'SCBD, Jakarta Selatan' },
    delivery: { date: '10 Sep 2026', time: '10:00–13:00', note: '' },
    message: 'Terima kasih atas kerja samanya.',
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    status: 'completed',
    settlement: 'available',
    createdAt: '8 Sep 2026',
    timeline: T('completed'),
  },
  {
    id: 'INV-2026-005',
    customerId: 'c-putri',
    customerName: 'Putri',
    items: [{ productId: 'prd-lily-oriental', name: 'Buket Lily Oriental Pink', img: G('b7696452f26e685c3a5a8d2ecdfcfb2e-800-161358b056.webp'), price: 290000, qty: 1, partnerId: 'pt-bali-tropis' }],
    partnerId: 'pt-bali-tropis',
    productTotal: 290000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 340000,
    recipient: { name: 'Ibu Wayan', phone: '0821xxxxxx', address: 'Denpasar' },
    delivery: { date: '14 Sep 2026', time: '10:00–13:00', note: '' },
    message: 'Sehat selalu ya Bu.',
    paymentMethod: 'qris',
    paymentStatus: 'unpaid',
    status: 'pending_payment',
    settlement: 'pending',
    createdAt: '13 Sep 2026',
    timeline: T('pending_payment'),
  },
  {
    id: 'INV-2026-006',
    customerId: 'c-rina',
    customerName: 'Rina',
    items: [{ productId: 'prd-alstro-pink', name: 'Buket Alstroemeria Pink Ceria', img: G('bc3dff37241196a134e14bc1a6216c62-480-6c122f0e3d.webp'), price: 149000, qty: 1, partnerId: 'pt-kebun-dieng' }],
    partnerId: 'pt-kebun-dieng',
    productTotal: 149000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 199000,
    recipient: { name: 'Dita', phone: '0819xxxxxx', address: 'Semarang' },
    delivery: { date: '9 Sep 2026', time: '10:00–13:00', note: '' },
    message: 'Congrats Dita!',
    paymentMethod: 'qris',
    paymentStatus: 'paid',
    status: 'accepted',
    settlement: 'pending',
    createdAt: '9 Sep 2026',
    timeline: T('accepted'),
  },
  {
    id: 'INV-2026-007',
    customerId: 'c-budi',
    customerName: 'Budi',
    items: [{ productId: 'prd-eucalyptus', name: 'Buket Eucalyptus Silver Dollar', img: G('9caffa42f100ae8ff1e3d86dc3f07c0a-244-cbc225d9a6.webp'), price: 135000, qty: 1, partnerId: 'pt-kebun-dieng' }],
    partnerId: 'pt-kebun-dieng',
    productTotal: 135000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 185000,
    recipient: { name: 'Keluarga Pak RT', phone: '0812xxxxxx', address: 'Bandung' },
    delivery: { date: '7 Sep 2026', time: '10:00–13:00', note: '' },
    message: 'Turut berduka cita.',
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    status: 'ready',
    settlement: 'pending',
    createdAt: '7 Sep 2026',
    timeline: T('ready'),
  },
  {
    id: 'INV-2026-009',
    customerId: 'c-budi',
    customerName: 'Budi',
    items: [{ productId: 'prd-standing-peach', name: 'Standing Flower Juliet Peach', img: G('831fd0b98e08fe217a7e37f4f54c445d-249-e6dc7924b5.webp'), price: 520000, qty: 1, partnerId: 'pt-flower-house' }],
    partnerId: 'pt-flower-house',
    productTotal: 520000,
    deliveryFee: 30000,
    platformFee: 20000,
    total: 570000,
    recipient: { name: 'Gedung Sasono Utomo', phone: '0812xxxxxx', address: 'TMII, Jakarta Timur' },
    delivery: { date: '6 Sep 2026', time: '08:00–10:00', note: 'Wedding jam 11' },
    message: 'Happy wedding!',
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    status: 'disputed',
    settlement: 'pending',
    createdAt: '6 Sep 2026',
    timeline: T('disputed'),
    dispute: { reason: 'Produk tidak sesuai pesanan — warna peach jadi pink', status: 'Under Review' },
  },
];

export const STATUS_LABEL: Record<string, string> = {
  pending_payment: 'Menunggu Pembayaran',
  paid: 'Dibayar',
  accepted: 'Diterima Partner',
  preparing: 'Disiapkan',
  ready: 'Siap Kirim',
  shipped: 'Dikirim',
  delivered: 'Diterima',
  completed: 'Selesai',
  disputed: 'Komplain',
  cancelled: 'Dibatalkan',
};

export const REVIEWS = [
  { name: 'Rina · Jakarta', text: 'Pilihnya gampang, bayar sekali, tinggal pantau sampai tiba. Praktis banget!', product: 'Buket Peony' },
  { name: 'Budi · Bandung', text: 'Status dananya jelas — tahu uang saya di tahap mana. Itu yang bikin berani pesan papan 2 unit.', product: 'Bunga Papan' },
  { name: 'Sinta · Surabaya', text: 'Buket wisuda sampai sebelum acara. Ada foto QC sebelum dikirim, jadi tenang.', product: 'Buket Tulip' },
];

export const FAQS = [
  { q: 'Siapa yang membuat pesanan saya?', a: 'Semua rangkaian dikurasi dan disiapkan oleh tim Bungapedia dengan standar foto QC sebelum dikirim.' },
  { q: 'Uang saya ke mana setelah bayar?', a: 'Dana tercatat dengan status Pending sampai kamu konfirmasi pesanan selesai. Kamu bisa pantau statusnya di halaman tracking.' },
  { q: 'Bagaimana kalau produk bermasalah?', a: 'Ajukan komplain dari halaman tracking. Tim Bungapedia akan membantu: refund, partial refund, atau pengiriman ulang.' },
  { q: 'Apakah Bungapedia toko bunga?', a: 'Ya — Bungapedia adalah toko rangkaian bunga & hadiah kurasi. Kamu pesan langsung dari Bungapedia, bukan dari pihak ketiga.' },
];
